### ISSUE TITLE
AVG compliant integration with IRMA?

### ISSUE THREAD

**Issue by mevdschee** [privacybydesign/angrygames#1]
The site https://www.angrygames.nl/ does not comply with the AVG* (on various points). One of the problems is that it is leaking personal information (IP address and user agent string) without consent to a third party (privacybydesign.foundation). I feel that when you make a demo to demo privacy compliant usage of IRMA, you should also take the AVG into account.

NB: Both parties (www.angrygames.nl) and (privacybydesign.foundation) cannot be identified as they are using "Domain Validation" for their SSL certificates, so I cannot assume it is the same organization (would also not make sense for the demo). I would recommend that privacybydesign.foundation domain uses an EV certificate, so that we can verify which organization is running that site.

NB2: Maybe if the IRMA QR code (and consequent status polling) would only be loaded after a click with the text "Let the Privacy Foundation verify my age with the IRMA app" it would comply as the user chooses to connect to the other domain and the functionality is required for operating the website.

*) see: https://www.yoursafetynet.com/nl/checklist-met-deze-10-stappen-maak-je-jouw-website-avg-proof/

**Comment by sietseringers** [comment]
Angrygames.nl does not leak personal information to a third party, because the Privacy by Design foundation is not a third party: it runs angrygames.nl. (Why would that not make sense?)

The website indeed does not make that clear - although angrygames.nl and privacybydesign.foundation share the same IP address and the source code is under the https://github.com/privacybydesign organization.

**Comment by sietseringers** [comment]
The website now [explicitly mentions](https://github.com/privacybydesign/angrygames/commit/71927165d7176e7f33a6a1d7bd86f3445039bff9) it is developed and hosted by the Privacy by Design Foundation.

**Comment by mevdschee** [comment]
>Why would that not make sense?

Because (I believe) this is a demo to show how a third party would use IRMA.

Can you re-open the issue until it is resolved?

**Comment by sietseringers** [comment]
Isn't it?

**Comment by mevdschee** [comment]
>Isn't it?

No, I believe this is a demo to show how a third party should integrate IRMA age validation into their website. Such an integration must comply with the AVG. Can you adjust the repository so that it shows how to do an AVG compliant integration with IRMA? It would make sense to pretend that angrygames is a third party or wouldn't it?

I adjusted the title of the issue to make the point more clear.

**Comment by sietseringers** [comment]
Ah, I see. It was indeed not clear to me that that is what you meant.

Well, that was not really the intention of this demo. Instead it is mostly used to showcase what the IRMA user experience might look like, for IRMA app users as well as potential attribute verifiers. For details as to how to integrate IRMA, one can best refer to the [IRMA technical documentation](https://irma.app/docs).

At any rate, it is not the point of this demo to teach people to connect to the IRMA server at https://privacybydesign.foundation to verify IRMA attributes. That IRMA server is used exclusively by the Privacy by Design Foundation, and no others; it will not even accept connections from third parties (which this website is not).

Instead, the preferred way for someone to integrate IRMA in their website is to run their own IRMA server in their own infrastructure. In that case, the one that runs the website also processes the personal data, so that neither the Foundation nor any other third party needs to be involved at all, unlike most other authentication mechanism/services. That is one of the primary privacy advantages that IRMA can achieve, and results in automatic GDRP compliance with regards to personal data/third parties.

**Comment by mevdschee** [comment]
Thank you for your explanation. It becomes more clear to me now, some remarks:

>Instead, the preferred way for someone to integrate IRMA in their website is to run their own IRMA server 

The simple question is: why is the demo not doing this then? The way the demo is setup make it look like IRMA requires central infrastructure.

Also note that having something called "mijn IRMA" (hosted on your domain) does not help to convey the decentralized message.

>That is one of the primary privacy advantages that IRMA can achieve, and results in automatic GDPR compliance with regards to personal data/third parties.

This is great to hear and I feel that this should be added as a claim (with your written explanation) to the project's description (README?). 

Note that even when not exchanging data with third parties the AVG may require you to have a privacy statement. Mentioning that this site is ran by a certain organization does not imply that that organization's privacy policy is applicable to this website. Especially as this website is not mentioned in that policy at all.

Also the app did not ask my permission before information (such as IP address and user agent string?) was sent to angrygames.nl while the [privacy statement](https://privacybydesign.foundation/privacy-policy/) says:

> Een IRMA gebruiker wordt bij iedere verwerking door de stichting Privacy by Design als verwerkingsverantwoordelijke, of door uitvoerder SIDN, expliciet om toestemming gevraagd.

Note that the privacy policy seems to suggest that I must accept crash reports to be sent and I cannot choose to NOT send those reports containing information:

>Wanneer de IRMA app crasht of een ernstig probleem tegenkomt wordt een rapport van de fout samengesteld en naar de stichting gestuurd. 

I hope that this is not true.

Summary:

- angrygames makes it look like IRMA is centralized
- angrygames seems to have no privacy policy
- the IRMA app seems to communicate with angrygames without consent
- the IRMA app seems to not comply with AVG with respect to crash reports

I would be very thankful if you would address each of these points.

**Comment by sietseringers** [comment]
> The simple question is: why is the demo not doing this then?

It does: angrygames.nl and privacybydesign.foundation are the same party, even if this is not immediately clear.

> The way the demo is setup make it look like IRMA requires central infrastructure.

I can see how it can cause this impression. However, as I already mentioned this website was meant mostly to showcase what the IRMA user experience might look like, instead of clearly demonstrating the involved privacy aspects. I would be happy to accept a PR here that explains this more clearly, however.

In the meantime, please note that the website links to [irma.app](https://irma.app) which mentions this in its [FAQ](https://www.irma.app/#faqs); irma.app links to the IRMA technical documentation which also explains this; and now this website also links to [privacybydesign.foundation](https://privacybydesign.foundation) which explains this [here](https://privacybydesign.foundation/irma-explanation/#architecture).

> * angrygames seems to have no privacy policy

I have now included a sentence in the footer mentioning that the Foundation's privacy policy applies.

> * the IRMA app seems to not comply with AVG with respect to crash reports

The Foundation's privacy policy was indeed incorrect on this point, thanks for pointing this out: these error reports are sent if and only if the corresponding toggle in the IRMA app settings is enabled. I have updated the privacy policy.

> * the IRMA app seems to communicate with angrygames without consent

The IRMA app communicates with the IRMA server at privacybydesign.foundation at two moments: just after you scanned the QR, to retrieve the list of attributes to be disclosed, and then after you consented to disclosing them in the IRMA app. As to the latter, there the user gives consent by pressing "Yes" to the question "Do you wish to disclose the following data to Privacy by Design Foundation?".

As to the former, indeed the IRMA app necessarily discloses the IP address of the user's device to the Foundation during this communication. However (short of using e.g. Tor which is not currently viable), there is no way to do this step without disclosing an IP address or something similar. In addition, I think this is standard: for example, it is not possible for you to retrieve with your browser the privacy policy of any website without disclosing your IP address to the remote server during that retrieval. So you have to disclose this data before you can even read, let alone provide explicit consent, to any privacy policy that might mention that during retrieving of said privacy policy you disclose your IP address. This happens daily for all internet users for all websites, and is standard and accepted. This is similar to the step in which the IRMA app retrieves the disclosure request.

Note that the IRMA server (necessarily) notices, but never logs IP addresses of any of the IRMA apps it communicates with.

**Comment by mevdschee** [comment]
Okay, so on these points:

> - angrygames makes it look like IRMA is centralized

You write:

>I would be happy to accept a PR here that explains this more clearly, however.

You may run configure/proxy your "irmago" server on another domain (angrygames) to make this more clear. No PR is going to change your infrastructure unfortunately.

> - angrygames seems to have no privacy policy

You fixed this, thank you.

> - the IRMA app seems to communicate with angrygames without consent

The necessity to communicate with (and sending an IP adress to) a third party is not the question. The question is whether or not the user expected/initiated the communication with the third party or that the user needs to be asked for consent to communicate with an external server. Can you verify whether or not this communication is in line with the promise in the privacy statement:

>Een IRMA gebruiker wordt bij iedere verwerking door de stichting Privacy by Design als verwerkingsverantwoordelijke, of door uitvoerder SIDN, expliciet om toestemming gevraagd.

To me it seems as if the communication does not meet this requirement.

Note: If I were to design this I would make the age proof a mathematical challenge on an external device (as it seems is the case) and let the user enter the answer to this challenge on the same pc/laptop that is used to access the website from (like OTP and banking apps work). This way you are not leaking information from the device that is used to store your identity (and may have another security level).

> - the IRMA app seems to not comply with AVG with respect to crash reports

You fixed this, thank you.

**Comment by mevdschee** [comment]
>As to the former, indeed the IRMA app necessarily discloses the IP address of the user's device to the Foundation during this communication. However (short of using e.g. Tor which is not currently viable).

NB: Thinking about it, it is funny you mention Tor. Exactly this strategy of leaking requests and IP addresses (that the IRMA app is doing) is used to defeat the privacy of users of Tor (browser). 

To help you with a use case think about the common use case of age validation before watching adult movies while using a VPN to avoid being blackmailed for such (legal) behavior by anyone listening to the wifi.

Or if you want a more serious use case: what about using IRMA to sign up as a member to an opposing political party over VPN/Tor in a country where the political parties in charge apply unlawful mass surveillance on their citizen?

**Comment by confiks** [comment]
Leak the IP address? Does IRMA circumvent the device's network settings? If not, it's only a leak insofar that it's a different device.

I would actually love if you would test for us (having a different device / situation) what happens if you configure a VPN on an (Android) phone and use IRMA. We've had some reports that due to using the gomobile network stack internally, there are some problems.

**Comment by sietseringers** [comment]
I have after further reflection modified the demo such that it shows `angrygames.nl` in the IRMA app as you suggested.

**Comment by mevdschee** [comment]
>it's only a leak insofar that it's a different device.

@confiks Indeed and that is the problem. When you use the tor/vpn browser to visit a site that requires you to verify your age and then have to use the irma app on your mobile phone. Your mobile phone cannot be (easily) used over tor/vpn and thus you are leaking and ip address (and potentially location). The IRMA app should not connect over the network (without consent) after scanning a QR code. In my opinion it should provide you with a number/letter sequence (as the banking apps do) so that you can enter that on the device you scanned the QR code from.

In the case that you are using the mobile phone to visit the site that requires age verification then the IRMA app does not need to scan a QR code and then I feel the proof should ideally be communicated back over the inter-app communication on the device (also not over the network). Note that the inter-app communication currently used by the IRMA app does work between Chrome and the IRMA app, but not between Firefox and the IRMA app (in my testing).

> using the gomobile network stack internally,

It is so awesome that you are working with gomobile! I really like this project (irma I mean). Great goals and great technology. Thank you for letting me contribute via these issues.

**Comment by mevdschee** [comment]
>I have after further reflection modified the demo such that it shows angrygames.nl in the IRMA app as you suggested.

Awesome, thank you very much. It looks much better this way! I see the polling request flow to the original domain as expected.

**Comment by sietseringers** [comment]
The privacy policy now mentions in which cases the user's IP is logged, including when scanning an IRMA QR with your IRMA app.

**Comment by mevdschee** [comment]
Thank you for making the demo better.

I would have liked a to read more clearly in the privacy policy that the keys of the personal information that is stored in the phone is managed by SIDN and that every access to personal information leads to the phone requesting these keys over the internet (I do read this, but it is not entirely clear to me). You might also add how the user chosen pin is a part of this encryption key.

(edit: translation)
